spring:
  datasource:
    password: Krishna7546@#
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
